// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCStudentRecordManagement.Models;

namespace TCStudentRecordManagement.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201007181935_Notices")]
    partial class Notices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TCStudentRecordManagement.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AssignmentID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CohortID")
                        .HasColumnName("CohortID")
                        .HasColumnType("int");

                    b.Property<string>("DocURL")
                        .HasColumnName("DocURL")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnName("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("Title")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TopicID")
                        .HasColumnName("TopicID")
                        .HasColumnType("int");

                    b.Property<int>("TypeID")
                        .HasColumnName("TypeID")
                        .HasColumnType("int");

                    b.HasKey("AssignmentID");

                    b.HasIndex("CohortID")
                        .HasName("FK_Assignment_Cohort");

                    b.HasIndex("TopicID")
                        .HasName("FK_Assignment_Topic");

                    b.HasIndex("TypeID")
                        .HasName("FK_Assignment_AssignmentType");

                    b.ToTable("assignments");

                    b.HasData(
                        new
                        {
                            AssignmentID = -1,
                            CohortID = -9999,
                            EndDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Classroom instruction",
                            TopicID = -1,
                            TypeID = -1
                        },
                        new
                        {
                            AssignmentID = -2,
                            CohortID = -9999,
                            EndDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Online self-study",
                            TopicID = -1,
                            TypeID = -2
                        },
                        new
                        {
                            AssignmentID = -3,
                            CohortID = -9999,
                            EndDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Break",
                            TopicID = -1,
                            TypeID = -3
                        },
                        new
                        {
                            AssignmentID = -4,
                            CohortID = -1,
                            DocURL = "http://does-not-exist.com/",
                            EndDate = new DateTime(2020, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2020, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tic-Tac-Toe",
                            TopicID = -2,
                            TypeID = -5
                        },
                        new
                        {
                            AssignmentID = -5,
                            CohortID = -1,
                            DocURL = "http://does-not-exist.com/",
                            EndDate = new DateTime(2020, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2020, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entity Framework Practice 2: Cars",
                            TopicID = -13,
                            TypeID = -4
                        },
                        new
                        {
                            AssignmentID = -6,
                            CohortID = -2,
                            DocURL = "http://does-not-exist.com/",
                            EndDate = new DateTime(2020, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2020, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "React/Redux Group Milestone 2",
                            TopicID = -7,
                            TypeID = -6
                        },
                        new
                        {
                            AssignmentID = -7,
                            CohortID = -2,
                            DocURL = "http://does-not-exist.com/",
                            EndDate = new DateTime(2020, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2020, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Personal Portfolio: Milestone 1",
                            TopicID = -15,
                            TypeID = -6
                        },
                        new
                        {
                            AssignmentID = -8,
                            CohortID = -2,
                            DocURL = "http://does-not-exist.com/",
                            EndDate = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2020, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Javascript Todo App",
                            TopicID = -4,
                            TypeID = -5
                        });
                });

            modelBuilder.Entity("TCStudentRecordManagement.Models.AssignmentType", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TypeID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Description")
                        .HasColumnType("varchar(50)");

                    b.HasKey("TypeID");

                    b.ToTable("assignment_types");

                    b.HasData(
                        new
                        {
                            TypeID = -1,
                            Description = "Classroom lectures"
                        },
                        new
                        {
                            TypeID = -2,
                            Description = "Online self-study"
                        },
                        new
                        {
                            TypeID = -3,
                            Description = "Break"
                        },
                        new
                        {
                            TypeID = -4,
                            Description = "Practice"
                        },
                        new
                        {
                            TypeID = -5,
                            Description = "Weekend assignment"
                        },
                        new
                        {
                            TypeID = -6,
                            Description = "Milestone"
                        },
                        new
                        {
                            TypeID = -7,
                            Description = "Capstone"
                        });
                });

            modelBuilder.Entity("TCStudentRecordManagement.Models.Attendance", b =>
                {
                    b.Property<int>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RecordID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttendanceStateID")
                        .HasColumnName("AttendanceStateID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnName("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("StaffID")
                        .HasColumnName("StaffID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnName("StudentID")
                        .HasColumnType("int");

                    b.HasKey("RecordID");

                    b.HasIndex("AttendanceStateID")
                        .HasName("FK_Attendance_AttendanceState");

                    b.HasIndex("StaffID")
                        .HasName("FK_Attendance_User");

                    b.HasIndex("StudentID")
                        .HasName("FK_Attendance_Student");

                    b.ToTable("attendance");

                    b.HasData(
                        new
                        {
                            RecordID = -1,
                            AttendanceStateID = -1,
                            Date = new DateTime(2020, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 6,
                            StudentID = -1
                        },
                        new
                        {
                            RecordID = -2,
                            AttendanceStateID = -2,
                            Date = new DateTime(2020, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 6,
                            StudentID = -4
                        });
                });

            modelBuilder.Entity("TCStudentRecordManagement.Models.AttendanceState", b =>
                {
                    b.Property<int>("StateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StateID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Description")
                        .HasColumnType("varchar(50)");

                    b.HasKey("StateID");

                    b.ToTable("attendance_states");

                    b.HasData(
                        new
                        {
                            StateID = -1,
                            Description = "Present"
                        },
                        new
                        {
                            StateID = -2,
                            Description = "Absent with notice"
                        },
                        new
                        {
                            StateID = -3,
                            Description = "Absent without notice"
                        });
                });

            modelBuilder.Entity("TCStudentRecordManagement.Models.Cohort", b =>
                {
                    b.Property<int>("CohortID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CohortID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnName("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CohortID");

                    b.ToTable("cohorts");

                    b.HasData(
                        new
                        {
                            CohortID = -9999,
                            EndDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            Name = "Common",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CohortID = -1,
                            EndDate = new DateTime(2020, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "4.1 Summer/Autumn 2020",
                            StartDate = new DateTime(2020, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CohortID = -2,
                            EndDate = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "4.2 Autumn/Winter 2020",
                            StartDate = new DateTime(2020, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TCStudentRecordManagement.Models.Notice", b =>
                {
                    b.Property<int>("NoticeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("NoticeID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CohortID")
                        .HasColumnName("CohortID")
                        .HasColumnType("int");

                    b.Property<string>("HTML")
                        .HasColumnName("HTML")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Markdown")
                        .HasColumnName("Markdown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffID")
                        .HasColumnName("StaffID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnName("ValidFrom")
                        .HasColumnType("datetime2");

                    b.HasKey("NoticeID");

                    b.HasIndex("CohortID")
                        .HasName("FK_Notice_Cohort");

                    b.HasIndex("StaffID")
                        .HasName("FK_Notice_User");

                    b.ToTable("notices");

                    b.HasData(
                        new
                        {
                            NoticeID = -1,
                            CohortID = -1,
                            StaffID = 6,
                            ValidFrom = new DateTime(2020, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            NoticeID = -2,
                            CohortID = -2,
                            StaffID = 6,
                            ValidFrom = new DateTime(2020, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TCStudentRecordManagement.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StudentID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BearTracksID")
                        .HasColumnName("BearTracksID")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("CohortID")
                        .HasColumnName("CohortID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnName("UserID")
                        .HasColumnType("int");

                    b.HasKey("StudentID");

                    b.HasIndex("CohortID")
                        .HasName("FK_Student_Cohort");

                    b.HasIndex("UserID")
                        .HasName("FK_Student_User");

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            StudentID = -1,
                            CohortID = -1,
                            UserID = 1
                        },
                        new
                        {
                            StudentID = -2,
                            CohortID = -1,
                            UserID = 2
                        },
                        new
                        {
                            StudentID = -3,
                            CohortID = -1,
                            UserID = 3
                        },
                        new
                        {
                            StudentID = -4,
                            CohortID = -2,
                            UserID = 4
                        },
                        new
                        {
                            StudentID = -5,
                            CohortID = -2,
                            UserID = 5
                        });
                });

            modelBuilder.Entity("TCStudentRecordManagement.Models.Timesheet", b =>
                {
                    b.Property<int>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RecordID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssignmentID")
                        .HasColumnName("AssignmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnName("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentID")
                        .HasColumnName("StudentID")
                        .HasColumnType("int");

                    b.Property<decimal>("TimeAllocation")
                        .HasColumnName("TimeAllocation")
                        .HasColumnType("decimal(3,2)");

                    b.HasKey("RecordID");

                    b.HasIndex("AssignmentID")
                        .HasName("FK_Timesheet_Assignment");

                    b.HasIndex("StudentID")
                        .HasName("FK_Timesheet_Student");

                    b.ToTable("timesheets");
                });

            modelBuilder.Entity("TCStudentRecordManagement.Models.Topic", b =>
                {
                    b.Property<int>("TopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TopicID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Description")
                        .HasColumnType("varchar(50)");

                    b.HasKey("TopicID");

                    b.ToTable("topics");

                    b.HasData(
                        new
                        {
                            TopicID = -1,
                            Description = "Generic"
                        },
                        new
                        {
                            TopicID = -2,
                            Description = "C# fundamentals"
                        },
                        new
                        {
                            TopicID = -3,
                            Description = "HTML5 and CSS"
                        },
                        new
                        {
                            TopicID = -4,
                            Description = "Javascript fundamentals"
                        },
                        new
                        {
                            TopicID = -5,
                            Description = "Javascript AJAX and API"
                        },
                        new
                        {
                            TopicID = -6,
                            Description = "React fundamentals"
                        },
                        new
                        {
                            TopicID = -7,
                            Description = "React/Redux"
                        },
                        new
                        {
                            TopicID = -8,
                            Description = "SQL fundamentals"
                        },
                        new
                        {
                            TopicID = -9,
                            Description = "Wordpress"
                        },
                        new
                        {
                            TopicID = -10,
                            Description = "PHP fundamentals"
                        },
                        new
                        {
                            TopicID = -11,
                            Description = "PHP APIs"
                        },
                        new
                        {
                            TopicID = -12,
                            Description = "C# OOP"
                        },
                        new
                        {
                            TopicID = -13,
                            Description = "C# Entity Framework"
                        },
                        new
                        {
                            TopicID = -14,
                            Description = "C# MVC"
                        },
                        new
                        {
                            TopicID = -15,
                            Description = "C# WebAPI"
                        },
                        new
                        {
                            TopicID = -16,
                            Description = "C# WebAPI and React"
                        });
                });

            modelBuilder.Entity("TCStudentRecordManagement.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("varchar(320)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnName("Firstname")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnName("Lastname")
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Rights")
                        .HasColumnName("Rights")
                        .HasColumnType("tinyint");

                    b.HasKey("UserID");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "john.dough@abc.com",
                            Firstname = "John",
                            Lastname = "Dough",
                            Rights = (byte)1
                        },
                        new
                        {
                            UserID = 2,
                            Email = "anne.jackson@abc.com",
                            Firstname = "Anne",
                            Lastname = "Jackson",
                            Rights = (byte)1
                        },
                        new
                        {
                            UserID = 3,
                            Email = "ivan.patterson@abc.com",
                            Firstname = "Ivan",
                            Lastname = "Patterson",
                            Rights = (byte)1
                        },
                        new
                        {
                            UserID = 4,
                            Email = "trevor.noah@abc.com",
                            Firstname = "Trevor",
                            Lastname = "Noah",
                            Rights = (byte)1
                        },
                        new
                        {
                            UserID = 5,
                            Email = "peter.patsie@abc.com",
                            Firstname = "Peter",
                            Lastname = "Patsie",
                            Rights = (byte)1
                        },
                        new
                        {
                            UserID = 6,
                            Email = "jane.smitherson@abc.com",
                            Firstname = "Jane",
                            Lastname = "Smitherson",
                            Rights = (byte)2
                        });
                });

            modelBuilder.Entity("TCStudentRecordManagement.Models.Assignment", b =>
                {
                    b.HasOne("TCStudentRecordManagement.Models.Cohort", "AssignmentCohort")
                        .WithMany("Assignments")
                        .HasForeignKey("CohortID")
                        .HasConstraintName("FK_Assignment_Cohort")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCStudentRecordManagement.Models.Topic", "AssignmentTopic")
                        .WithMany("Assignments")
                        .HasForeignKey("TopicID")
                        .HasConstraintName("FK_Assignment_Topic")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TCStudentRecordManagement.Models.AssignmentType", "Type")
                        .WithMany("Assignments")
                        .HasForeignKey("TypeID")
                        .HasConstraintName("FK_Assignment_AssignmentType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TCStudentRecordManagement.Models.Attendance", b =>
                {
                    b.HasOne("TCStudentRecordManagement.Models.AttendanceState", "AttendanceType")
                        .WithMany("AttendancesOfType")
                        .HasForeignKey("AttendanceStateID")
                        .HasConstraintName("FK_Attendance_AttendanceState")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TCStudentRecordManagement.Models.User", "RecordedBy")
                        .WithMany()
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCStudentRecordManagement.Models.Student", "StudentDetails")
                        .WithMany("AttendanceRecord")
                        .HasForeignKey("StudentID")
                        .HasConstraintName("FK_Attendance_Student")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TCStudentRecordManagement.Models.Notice", b =>
                {
                    b.HasOne("TCStudentRecordManagement.Models.Cohort", "ForCohort")
                        .WithMany("Notices")
                        .HasForeignKey("CohortID")
                        .HasConstraintName("FK_Notice_Cohort")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TCStudentRecordManagement.Models.User", "Staff")
                        .WithMany("Notices")
                        .HasForeignKey("StaffID")
                        .HasConstraintName("FK_Notice_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TCStudentRecordManagement.Models.Student", b =>
                {
                    b.HasOne("TCStudentRecordManagement.Models.Cohort", "CohortMember")
                        .WithMany("Students")
                        .HasForeignKey("CohortID")
                        .HasConstraintName("FK_Student_Cohort")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TCStudentRecordManagement.Models.User", "UserData")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TCStudentRecordManagement.Models.Timesheet", b =>
                {
                    b.HasOne("TCStudentRecordManagement.Models.Assignment", "AssignmentAlloc")
                        .WithMany("Timesheets")
                        .HasForeignKey("AssignmentID")
                        .HasConstraintName("FK_Timesheet_Assignment")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TCStudentRecordManagement.Models.Student", "ForStudent")
                        .WithMany("Timesheets")
                        .HasForeignKey("StudentID")
                        .HasConstraintName("FK_Timesheet_Student")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
